### ISSUE TITLE
close tab shortcut key is broken

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/zxlive#113]
When trying to close a tab using the `Ctrl+W` shortcut, nothing happens, and the error message `QAction::event: Ambiguous shortcut overload: Ctrl+W` is displayed in the console.

This seems to be due to this line in `mainwindow.py`:
`close_action.setShortcuts([QKeySequence(QKeySequence.StandardKey.Close), QKeySequence("Ctrl+W")])`

Removing this line fixes the error, allowing `Ctrl+W` to close the tab.

This might be OS-specific, as the standard tab `Close` key is already `Ctrl+W` key on some systems. Presumably, that line was added to handle `Ctrl+W` as a shortcut on a system where it isn't already the default.

**Comment by dlyongemallo** [comment]
According to [the documentation](https://doc.qt.io/qt-6/qkeysequence.html), `Ctrl+W` is already included as a standard key for close in all supported OSes, so it should be safe to just remove that line.

| StandardKey | Windows         | macOS           | KDE Plasma | GNOME  |
|-------------|-----------------|-----------------|------------|--------|
| Close       | Ctrl+F4, Ctrl+W | Ctrl+W, Ctrl+F4 | Ctrl+W     | Ctrl+W |

**Comment by dlyongemallo** [comment]
The doc also says that on macOS, `Ctrl` corresponds to the `Command` key (rather than the key actually labelled `Control` on the mac keyboard), so maybe that line was intended to fix that?

**Comment by RazinShaikh** [comment]
Ctrl+W closes the tab on windows. Maybe it's mac specific?

**Comment by dlyongemallo** [comment]
Exactly, `Ctrl+W `already closes the tab on Windows, by default, so that line is unnecessary. Same for GNOME/KDE. So the only reason for that line would be to make it so that `Control+W` works in addition to `Command+W` on macOS.

Nevertheless, the fact that adding the default `Close` key already adds `Ctrl+W`, which then conflicts with the explicit addition of `Ctrl+W`, seems to be a bug in QT6 (which is maybe the same as [this one](https://bugreports.qt.io/browse/QTBUG-112193)).
