### ISSUE TITLE
Cannot install dependencies due to python 3.11

### ISSUE THREAD

**Issue by contra-bit** [Quantomatic/zxlive#119]
Good evening dear maintainers,

I have tried installing zxlive in an virtual environment using `pip install .` but i get this error:

```
ERROR: Could not find a version that satisfies the requirement PySide6 (from zxlive) (from versions: none)
```

When running `pip install -r requirements` I get the following error
```
ERROR: Ignored the following versions that require a different python version: 1.21.2 Requires-Python >=3.7,<3.11; 1.21.3 Requires-Python >=3.7,<3.11; 1.21.4 Requires-Python >=3.7,<3.11; 1.21.5 Requires-Python >=3.7,<3.11; 1.21.6 Requires-Python >=3.7,<3.11
ERROR: Could not find a version that satisfies the requirement PySide6~=6.5.2 (from versions: none)
ERROR: No matching distribution found for PySide6~=6.5.2
```

Could you please add support for python 3.11 or a note specifying which versions are supported

Thank you very much.

**Comment by dlyongemallo** [comment]
Can you give a bit more info about your system? For example, what OS are you running?

What's the output of the following commands?

```
python --version
pip --version
pip install PySide6~=6.5.2
```

**Comment by dlyongemallo** [comment]
Just to be clear, I'm not a maintainer. But I was able to run zxlive on python 3.11, so the python version by itself is not the problem.

**Comment by RazinShaikh** [comment]
We can close this for now but feel free to reopen if you still have problems.
