### ISSUE TITLE
Consistent naming conventions

### ISSUE THREAD

**Issue by akissinger** [Quantomatic/zxlive#12]
For consistency (and generally not getting weird-looking code), I suggest we adopt PEP 8 naming conventions where ever possible/reasonable:

https://peps.python.org/pep-0008/#naming-conventions

The main exception to this is the Qt bindings, which are all C++ style. The accepted convention is to use Python naming for your own code and Qt conventions just for calling/overriding Qt things.

In particular, capital letters and underscores should (almost) never go together. This looks very strange to me.

Also, I suggest avoiding writing the type of a thing in variable names, e.g. the many variables called `Button_....`. The exception to this is if there is only one thing of a given type around, e.g. a `graph_view` of type `GraphView`.

**Comment by mark-koch** [comment]
Hey, I could have a go at this if no one has started working on it yet? I wanted to go over everything anyways to get to know the codebase

**Comment by devilkiller-ag** [comment]
Hey, Can I also work on this?

**Comment by natestemen** [comment]
@jvdwetering @akissinger please ensure @mark-koch is assigned to this issue when you get a chance to we can ensure he is awarded the bounty!
