### ISSUE TITLE
Support rewriting Hadamard edge

### ISSUE THREAD

**Issue by king-p3nguin** [Quantomatic/zxlive#125]
It would be nice if zxlive supports rewriting the Hadamard edge:

<img src="https://upload.wikimedia.org/wikipedia/commons/e/e2/ZX-calculus_Hadamard_scalar-free_Euler_decomposition_rule.svg" width="400" />

**Comment by RazinShaikh** [comment]
ZXLive supports custom rewrites so you can add this as a custom rewrite in the Rewrite menu

**Comment by king-p3nguin** [comment]
Oh, I did not know that. Thank you!
