### ISSUE TITLE
Make colours user-adjustable (and preferences savable).

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#135]
Converting this to an issue from the QPL checklist

**Comment by jvdwetering** [comment]
I implemented this in [c26a89f](https://github.com/Quantomatic/zxlive/commit/c26a89f7f0df8d01ad2c3ac10bda0a36f0747976), just have to also do this for edge colours still. And perhaps we want to add a couple more colour schemes (like the one used by PsiQuantum).

**Comment by RazinShaikh** [comment]
While it's really nice to have a list of pre-defined colour schemes, will it be too much work to make it entirely customizable where you can pick a colour for each generator?

**Comment by jvdwetering** [comment]
Probably wouldn't be too hard to implement, but I also didn't see a clear reason to implement that yet.

**Comment by jvdwetering** [comment]
This fully works now.
