### ISSUE TITLE
Show matrix raises exception if parameters are present in the diagram

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#145]
Reproduce: create a well-formed diagram with a parameter. Then click Show matrix.
Output:
```
Traceback (most recent call last):
  File "C:\Users\jvdwe\Documents\Projects\zxlive\zxlive\mainwindow.py", line 462, in show_matrix
    matrix = self.active_panel.graph.to_matrix()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdwe\Documents\Projects\zxlive\../pyzx\pyzx\graph\base.py", line 458, in to_matrix
    return tensor_to_matrix(tensorfy(self, preserve_scalar), self.num_inputs(), self.num_outputs())
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdwe\Documents\Projects\zxlive\../pyzx\pyzx\tensor.py", line 149, in tensorfy
    t = H_to_tensor(d,phase)
        ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jvdwe\Documents\Projects\zxlive\../pyzx\pyzx\tensor.py", line 72, in H_to_tensor
    if phase != 0: m[-1] = np.exp(1j*phase)
                                  ~~^~~~~~
  File "C:\Users\jvdwe\Documents\Projects\zxlive\zxlive\poly.py", line 141, in __mul__
    for c2, t2 in other.terms:
                  ^^^^^^^^^^^
AttributeError: 'complex' object has no attribute 'terms'
```

**Comment by RazinShaikh** [comment]
What should be the output? A matrix with symbolic values or just an error to the user in the UI?

**Comment by jvdwetering** [comment]
Either. The first is of course preferable, but I don't know how difficult that would be.

**Comment by dlyongemallo** [comment]
The problem here is that pyzx isn't aware of `Poly` phases, and is trying to stuff a named variable into the argument of `numpy.exp`. This is possible to carry out using `sympy.exp` instead, but the pyzx needs to be aware of symbolic values and act appropriately.

I would take a bit of work to make pyzx aware of symbolic variables, however, maybe this is an important use case and is worth doing?

**Comment by RazinShaikh** [comment]
I would say symbolic variables are very important. It is commonly used for reasoning in many papers.

**Comment by dlyongemallo** [comment]
What is the reason there's a custom `Poly` class, as opposed to using something like `sympy` directly?

**Comment by jvdwetering** [comment]
I think the idea was to have something lightweight where we also have better control over the behaviour. For instance, `beta` is a function in `sympy` instead of being able to denote a variable like it often does in ZX papers. In addition, we want to distinguish between two different types of variables, continuous ones and Boolean ones and have different rewrite logic based on that. The reasoning is explained in #60.
