### ISSUE TITLE
should `Poly` live in the pyzx library instead of here?

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/zxlive#152]
In zxlive, phases are sometimes represented as `Poly`. Under some circumstances, these are passed into the pyzx library, which isn't aware of them (and is expecting `float` or `Fraction`). For the most part, since `Poly` defines the addition and multiplication operators, things just "work out". However, from a type-checking and debugging point of view, this isn't really a correct design and will probably lead to bugs in the future. If pyzx is intended to be called with `Poly` phases, then `Poly` should either live in that library, or it should at least be aware of such a type.

**Comment by dlyongemallo** [comment]
For example, issue #145 shows an example where a `Poly` object has been passed into pyzx's `H_to_tensor`, where it is expecting a `float`.

**Comment by RazinShaikh** [comment]
Indeed. Many methods in PyZX such as ones related to saving fail because it's not aware of Poly.

**Comment by RazinShaikh** [comment]
Poly has now been moved to pyzx
