### ISSUE TITLE
Changing colour scheme should also change the colours of the node selection panel

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#174]
The colour scheme does not affect the colours in the right pannel.

![image](https://github.com/Quantomatic/zxlive/assets/28257517/ebf2eb8f-f87d-4e81-8753-7232300143c3)

**Comment by jvdwetering** [comment]
So I was thinking we can maybe have a 'some changes will only work after a restart' text in the settings panel. That might be one way to go about it.

**Comment by RazinShaikh** [comment]
I didn't realize that this was already implemented. It makes sense to simply ask the user to restart then.

**Comment by jvdwetering** [comment]
Fixed in #176
