### ISSUE TITLE
Spider unfusion with phases

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#175]
We can use the magic wand to unfuse a spider. However, when the spider has a phase, the entire phase is given to one of the unfused spiders. The user may want to split the phase between the two unfused spiders: for example, split the phase 7pi/12 into pi/3 and pi/4. Add a way to perform this more general kind of unfusion.

**Comment by jvdwetering** [comment]
Maybe a pop-up window? With the phase of the spider on the left and the right

**Comment by RazinShaikh** [comment]
Something like that, but we only need the phase on the left as the phase on the right is determined by the total phase.

**Comment by RazinShaikh** [comment]
Completed in dba9c5d58a808b78b7cce91b5bc0c8e05b13af92
