### ISSUE TITLE
Oxford Hackathon 13/11/2023

### ISSUE THREAD

**Issue by boldar99** [Quantomatic/zxlive#179]
- [x] Quantum circuit builder (Mark)
- [x] Refresh rewrites (Giovanni)
- [x] Magic wand phase unfuse (Tuomas)
- [x] Magic wand W-spider unfuse (Tuomas)
- [ ] https://github.com/Quantomatic/zxlive/issues/188
- [x] Export proof to Tikz with rewrite steps (Mark)
- [x] Logo (John)
- [ ] Icons for rewrites
- [x] #195 (Richie)
- [x] https://github.com/Quantomatic/zxlive/pull/184 (Lia)
- [x] https://github.com/Quantomatic/zxlive/pull/187 Improve UI - fix rewrite overflows (Boldi)
- [ ] #190
- [x] Custom rewrites with parametric phases (Razin)
- [x] Save diagrams with parameters (John)
- [ ] PyZX Parallel edges (Aleks)
- [ ] #192 
- [ ] MyPy compliance

**Comment by jvdwetering** [comment]
Closing this, as it has served its purpose.
