### ISSUE TITLE
Magic wand unfuse phases does not work

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#196]
When you hold shift + magic wand, it should unfuse phases but that does not seem to work anymore

**Comment by dlyongemallo** [comment]
Can you elaborate on what this means or give an example (screenshot or video)?

**Comment by RazinShaikh** [comment]
I just tested this and it seems to be working. Not sure why this was broken 6 months ago.

https://github.com/Quantomatic/zxlive/assets/28257517/f1c53e00-7346-4c30-aefc-6f97246d80c1

**Comment by jvdwetering** [comment]
I think there was a bug in the parsing of the phase expression that has since been fixed.
Should we go ahead and close this issue?

**Comment by dlyongemallo** [comment]
Seems to work for me too. I think this can be closed.
