### ISSUE TITLE
icons are missing on Windows

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/zxlive#208]
Normally I use ZXLive on Linux, but this morning I booted into Windows to test something and noticed that the icons were gone:

![image](https://github.com/Quantomatic/zxlive/assets/9248532/6eeb595b-2fbf-43ee-bbf8-26320432e6d0)

**Comment by jvdwetering** [comment]
It looks fine on my Windows machine. Are you working from source, or the exe?

**Comment by jvdwetering** [comment]
And are there files in your zxlive/icons folder?

**Comment by dlyongemallo** [comment]
Yes, the icons are there, and I can otherwise open them (in a browser or whatever). 

I'm running Windows 11. Which version of Windows are you running?

Anyone else seeing this problem?

**Comment by jvdwetering** [comment]
It also works fine on my Windows 11 machine. My Windows 10 machine also showed this fine.

**Comment by RazinShaikh** [comment]
It also works on my windows 11 device

**Comment by dlyongemallo** [comment]
Okay, apparently my computer has gremlins.

**Comment by jvdwetering** [comment]
I'm closing this. If other people have the same issue we can reopen.
