### ISSUE TITLE
Edge selection and unfusion

### ISSUE THREAD

**Issue by y-richie-y** [Quantomatic/zxlive#21]
There are many ways to unfuse a single spider.
![image](https://github.com/Quantomatic/zxlive/assets/13847804/da307f6c-ec9c-4541-8c56-4e0c5ab01a17)

If we support edge selection, then the un-fusion interaction can be done by picking a node and a subset of its edges.

**Comment by jvdwetering** [comment]
So something that was on my wishlist for the PyZX Jupyter editor is that you could make a 'slice' motion over a spider to split the spider into a spider with legs on one side of the slice and a spider with legs on the other side of the slice.
How do people feel about such an interface?
This wouldn't work for complicated splittings, but it would probably be enough for most cases.

**Comment by akissinger** [comment]
I like it!

This might get tricky for edges that are close together or to unfuse zero legs from a spider (i.e. introduce a state).

**Comment by jvdwetering** [comment]
This is now superceded by the Magic Wand #40.
