### ISSUE TITLE
import from tikz after export is broken

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/zxlive#211]
Repro steps (file attached [broken_tikz_import_repro.zip](https://github.com/Quantomatic/zxlive/files/13627537/broken_tikz_import_repro.zip)):
1. open the "3 CNOTs = SWAP.zxp" file.
2. export to tikz
3. open the resulting tikz file

Expected: tikz file is imported

Actual: error message "too many values to unpack (expected 2)".

**Comment by dlyongemallo** [comment]
I just saw #203. I guess this is related to that.

**Comment by jvdwetering** [comment]
Yeah exporting a proof to tikz is currently a one-way operation. There is no easy way to separate out the proof steps from just a single tikz file, so I'm not even sure this is something we would want to support.

**Comment by jvdwetering** [comment]
Maybe it can be made more clear to the user that tikz export of proofs is not intended to be two-way.
