### ISSUE TITLE
should `FractionLike` include `complex`?

### ISSUE THREAD

**Issue by dlyongemallo** [Quantomatic/zxlive#225]
Currently, `FractionLike` is defined as `Union[Fraction, int, Poly]` in [pyzx/utils.py](https://github.com/Quantomatic/pyzx/blob/c657667529918acf85d584e43ac73592ad3f2505/pyzx/utils.py#L26).

The [`_unfuse` function](https://github.com/Quantomatic/zxlive/blob/f99684358ecb1adb7cea0e357c84c49c58b64568/zxlive/proof_panel.py#L331) takes a `phase` which is `FractionLike`. It performs subtraction or division using this as the second operand.

A [recent change](https://github.com/Quantomatic/zxlive/commit/e7a2c691f3cd163d89e3dff5df2dff54665c9049) made it possible to [call `_unfuse`](https://github.com/Quantomatic/zxlive/blob/f99684358ecb1adb7cea0e357c84c49c58b64568/zxlive/proof_panel.py#L283) with [a `phase` which is `complex`](https://github.com/Quantomatic/zxlive/blob/f99684358ecb1adb7cea0e357c84c49c58b64568/zxlive/proof_panel.py#L252). 

Should `_unfuse` take a parameter which is typed `Union[FractionLike, complex]`, or should the definition of `FractionLike` be changed to include `complex` as one of the possibilities? Yet another possibility is to subsume `complex` into `Poly`.

But it seems to me in any case that anywhere where `FractionLike` is used, potentially a `complex` value could also be used.

**Comment by jvdwetering** [comment]
Currently complex-valued phases are not implemented as existing as a possible value on g.phase(), since the complex numbers of Z-boxes are treated using a vertexdata property. Since pretty much all the functionality of pyzx is based on spiders, and not Z-boxes, I don't see much value in changing this currently. Updating call_unfuse then makes more sense.

**Comment by dlyongemallo** [comment]
Okay, in that case this has just been fixed in https://github.com/Quantomatic/zxlive/pull/226/commits/22fab452e3b89e1468f4fe4af12fc0a21bfc4735 (which changes `_unfuse` to take in type `Union[FractionLike, complex]` for the `phase`).
