### ISSUE TITLE
Rewrite rules do not save when boundary nodes are on the same column

### ISSUE THREAD

**Issue by BenjaminRodatz** [Quantomatic/zxlive#242]
For some rewrite rules, the save function does not react, no matter what one does. This is likely because auto_detect_io() does not work. However, something like an error message would be useful. 

Example: 
<img width="530" alt="image" src="https://github.com/Quantomatic/zxlive/assets/38665964/e03b2391-88fb-4318-b98c-b764e9b9986e">

**Comment by RazinShaikh** [comment]
auto_detect_io() already shows a warning message
