### ISSUE TITLE
Importing and Exporting the diagram

### ISSUE THREAD

**Issue by y-richie-y** [Quantomatic/zxlive#3]
We would like to import and export diagrams from pyzx and other formats. pyzx has converters for some of these libraries so not all of this has to be done from scratch.

Requirements:
- [ ] QGraph support
- [x] tikz support
- [ ] QASM support
- [ ] Export to plain text / json

We potentially want to inherit the graph class in `pyzx` to handle parallel and directed edges.

**Comment by jvdwetering** [comment]
Just to add: pyzx has `to_tikz()`, `from_tikz`, `to_qasm()`, `from_qasm()`, `to_json()` and `from_json` methods for the graphs, this last one is the Quantomatic QGraph format.

**Comment by pandey-tushar** [comment]
Should we just use these functions from pyzx or do we write it ourselves (pretty much the same as pyzx)?

**Comment by akissinger** [comment]
Wherever possible, use pyzx and avoid re-implementing stuff.

**Comment by akissinger** [comment]
Another comment: I think we should think of one of these formats (probably qgraph) as "native" and use this for loading and saving. The native format should be able to store a faithful representation of the graph.

For the others, this should be implemented via "import" and "export" where it makes sense. For example, QASM could be imported (but exporting is not obvious) and tikz could be exported (but importing is a bit strange, although it has been implemented in pyzx).

If we do go with qgraph format, I suggest a new file extension (e.g. `zxgraph`), to avoid a (very) small minority of people trying to open ZX Live graphs in Quantomatic or vice versa.

**Comment by king-p3nguin** [comment]
I'm interested in working on this issue as part of the Unitary Hack. Can I be assigned to this challenge?
Thank you!

**Comment by jvdwetering** [comment]
Thanks @king-p3nguin! Very nice work. Yes, you can claim the bounty.

**Comment by king-p3nguin** [comment]
Hi @jvdwetering, it seems like other account is assigned to this issue. Would you assign me so that [this page](https://unitaryhack.dev/projects/zx-live/) will show the correct account who closed the issue?
