### ISSUE TITLE
Minimum Python version

### ISSUE THREAD

**Issue by mark-koch** [Quantomatic/zxlive#33]
We should decide on a minimum Python version to support and add it to `pyproject.toml`

For example, I'd like to use match statements from Python 3.10

**Comment by jvdwetering** [comment]
PyZX requires 3.7, so that the minimum should definitely be at least that. 3.8 has the end of support in a little over a year, so I think targetting at least 3.9 should be fine. So I'm not opposed to requiring Python 3.10.

**Comment by jvdwetering** [comment]
I think we have decided to use Python 3.10
