### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#34]
Things like undo and redo should definitely be using the ctrl+Z / ctrl+shift+Z keyboard shortcuts. I'm guessing this shouldn't be too hard to implement using builtin Qt features.

**Comment by jvdwetering** [comment]
I've now added this for a lot of standard actions (namely, all those actions that have been implemented):
* Saving as new file
* Opening
* Opening a new graph
* Undoing
* Redoing
* Cut
* Copy
* Paste
* Delete

**Comment by RazinShaikh** [comment]
Should this be closed?

**Comment by jvdwetering** [comment]
Yes, although I think we should have some standard that pretty much any action you would want to do with some regularity should have a keyboard shortcut.

**Comment by RazinShaikh** [comment]
I guess that would be something to mention in the CONTRIBUTORS file.
