### ISSUE TITLE
Magic wand features

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#40]
We discussed the features the magic wand should have. They are:

- [x] Slicing in a straight line over a spider, unfuses it with the wires on the left of it on one spider, and the other wires on the -other spider.
- [x] We also want this to work for curved lines for more complicated unfusions (in particular allowing you to unfuse a spider with zero wires).
- [x] Slicing over an identity spider should remove the spider.
- [x] Slicing over a wire should allow you to add an identity or a pair of Hadamards. It is not yet decided yet how the interface for choosing between these should be.

UI:
- [x] Slicing over a spider should highlight the spider in the same way that dragging does.
- [x] The sliced spiders should end up on the right side of the split.
- [x] The phase of the spider should end up on the left if you drag top-to-bottom, and to the right otherwise
- [x] More sparkles and colour!

**Comment by RazinShaikh** [comment]
Should this be closed?
