### ISSUE TITLE
GraphDiff functionality

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#45]
Right now most of the rewrite commands are implemented by SetGraph, which just replaces the entire graph. This is undesirable for various reasons. We should probably use some smarter GraphDiff functionality. This should probably be implemented in PyZX itself, and then interfaced in ZXLive to do a command more smartly.

**Comment by jvdwetering** [comment]
This is now implemented, and exists in the newest github version of PyZX, but is not yet pushed in PyZX to a release.

**Comment by RazinShaikh** [comment]
I guess it's okay to close this issue since there are several PyZX features used by zxlive that are not released yet.
