### ISSUE TITLE
Vertex movement is slightly broken

### ISSUE THREAD

**Issue by mark-koch** [Quantomatic/zxlive#55]
Move a single vertex. Then select all vertices and move them around together: you'll see some jumpy behaviour of the first vertex.

In general, vertices don't seem to snap to the grid properly

I guess this probably is some rounding error

**Comment by mark-koch** [comment]
I did a dirty fix in 2ad01c4 by making `OFFSET_X`  and `OFFSET_X` multiples of `SCALE` but this doesn't feel elegant.

We should probably revisit the grid snapping and grid drawing code to solve this in a better way

**Comment by jvdwetering** [comment]
I think that this solution is fine actually. Sure it's a bit hacky, but I don't think it's gonna bite us later (famous last words, I know).
