### ISSUE TITLE
Improving the GUI

### ISSUE THREAD

**Issue by y-richie-y** [Quantomatic/zxlive#6]
We want to make zxlive look more like [TIKZIT](https://tikzit.github.io/), which most of the ZX community are already familiar with using. Their GUI is implemented using Qt, so hopefully it isn't too hard to port the interface to zxlive.

Features:
- [ ] Adding nodes using right click
- [ ] Adding edges using right click + drag
- [ ] Separation between rewriting and editing modes

**Comment by akissinger** [comment]
Note that QGraphicsScene and QGraphicsItem already have selection support. we should use this where possible. Have a look at the methods containing the word "select" in the docs:

https://doc.qt.io/qt-6/qgraphicsscene.html
https://doc.qt.io/qt-6/qgraphicsitem.html

n.b. the Qt for python docs tend to be very minimal. Best to read the main Qt (C++) docs. The names and types are all the same as the python bindings.

**Comment by akissinger** [comment]
Made selection its own issue #23 .

**Comment by yosun** [comment]
What if it's a computer vision powered app that turns your diagram into LaTeX?

**Comment by jvdwetering** [comment]
That would be a great feature, but I think there is a lot more fundamental things that would have to be implemented first to make this thing usable.

**Comment by king-p3nguin** [comment]
Hi, I am working on this issue as part of the Unitary Hack, and I would like to be assigned to this issue after successfully merging the PR.
Thank you!

**Comment by natestemen** [comment]
Congrats @king-p3nguin for the successful hack! @jvdwetering I noticed that both @king-p3nguin and @Econ01 are assigned to this issue, but it looks like @king-p3nguin was the one to complete the bounty. Can you make sure only the hacker(s) that completed the bounty are assigned?
