### ISSUE TITLE
Transform menu should only be activated in proof mode

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#61]

**Comment by RazinShaikh** [comment]
Fixed in e63a8f53b7fd7f83c30cc8058a231c227571724c

**Comment by jvdwetering** [comment]
Right now it literally does not show the Simplify menu in edit mode. Do we want to change this to just gray it out? The usual behaviour of apps is that the menu bar at the top doesn't really change, right?

**Comment by RazinShaikh** [comment]
I am not sure what the right behaviour is. Maybe these simplifications should not be in the menu bar. Anyway, if you want to not change the menu bar, it is a simple change from setVisible to setEnabled.
