### ISSUE TITLE
Support custom rewrites / lemmas

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#66]
Allow users to define their own rewrite rules or prove lemmas, which they can apply in the proofs. This requires more thinking and is not urgent, but I am opening this issue as I think this is an important feature for a realistic use-case of zxlive.

**Comment by jvdwetering** [comment]
So I agree that something like this would be great to have. I see two different ways we could go about this.

One is to allow people to write custom python scripts that implement a matcher and a rewriter in just the way that pyzx does it. We could for instance make it that people put these in a standard location and that they are then automatically found. Or that people manually import these custom rewrites.

Two is to have an interface inside of ZXLive where people define a left-hand side and a right-hand side, and we use some kind of subgraph isomorphism matching to find out where to match it. The question here is how general we make this. I at least vote no bang-boxes.

**Comment by RazinShaikh** [comment]
I vote for the second option. We should start by making it not general at all. To apply a rewrite, the user has to select the exact nodes of the LHS of the rewrite. Then, we simply need to check if selection matches the LHS exactly, which is the graph isomorphism problem. In practice, the diagrams can be arbitrary large but rewrites usually don't grow as much, so this will not slow down zxlive.
