### ISSUE TITLE
UI improvement: Rewrite rules

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#71]
The side panel can have the rewrites, simplification routines and the proof steps. The code for sidebar of edit mode might be useful for implementing this.

**Comment by RazinShaikh** [comment]
Using tabs sounds like a nice idea :)

**Comment by boldar99** [comment]
We could do something like that of VSCode.

Rewrites on the side with collapsable groups. We could also implement searching and scrolling.

![image](https://github.com/Quantomatic/zxlive/assets/49209650/49858b00-7d68-40ba-8aa7-ca7d0b020bd1)

**Comment by RazinShaikh** [comment]
We should also allow the user to delete custom rewrites from the UI.

**Comment by jvdwetering** [comment]
I've now added the tabbed interface for different groups of rewrites.
![image](https://github.com/Quantomatic/zxlive/assets/15610543/1126c427-f9bb-464f-b173-e145b1db0165)

**Comment by jvdwetering** [comment]
I think we could also add different tab names based on subfolders in the folder containing the custom rewrite rules. This would make sense if we expect people to be adding a lot of custom rewrite rules.

A design decision we want to consider is whether a rewrite rule can appear in multiple tabs. For instance, should Z-spider fusion only appear in Basic rules, or also in the ZXW rule set and the ZH rule set?

**Comment by RazinShaikh** [comment]
Is it possible to add an option to change from horizontal tabs to vertical tabs? Most browsers support this. That would look a bit like Boldi's suggestion.

**Comment by RazinShaikh** [comment]
@jvdwetering can you also add these simplifications as a tab?

![image](https://github.com/Quantomatic/zxlive/assets/28257517/807ab9d8-6cb3-42d2-8aa8-0c9701e59ebf)

**Comment by jvdwetering** [comment]
> Is it possible to add an option to change from horizontal tabs to vertical tabs? Most browsers support this. That would look a bit like Boldi's suggestion. I fell that horizontal list of rewrites is a bit inconvenient if you have a lot of custom rewrites because then you need to scroll horizontally.

I believe there is some built in Qt feature that allows you to switch being a horizontal layout and a vertical layout.

**Comment by RazinShaikh** [comment]
I have added these simplification routines in this commit https://github.com/Quantomatic/zxlive/commit/a3d6260512b342577ca458029e18c5c6a1d03c1c

**Comment by RazinShaikh** [comment]
The horizontal tabbed interface we have here does not scroll when the there are a lot of rewrites and it compresses the text on the button such that you can't read the full name of the rewrite.
