### ISSUE TITLE
Auto detection of number of input and output doesn't auto-update all of the vertices when you move things around.

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#79]
The detection starts correctly:
![image](https://github.com/Quantomatic/zxlive/assets/15610543/0561199d-6c08-473b-bb38-3bb4848abbd1)

But then I move a vertex and only the vertex that is moved changes its numbers, not the others.
![image](https://github.com/Quantomatic/zxlive/assets/15610543/62d425d5-b88c-4c1a-bb0f-55ed585fd5df)

**Comment by RazinShaikh** [comment]
That because it's actually showing the integer part of the qubit attribute.

**Comment by jvdwetering** [comment]
Ah right. So not the spot in the list of g.inputs().

**Comment by RazinShaikh** [comment]
I guess it would make more sense for it to be the spot in the list of g.inputs().
