### ISSUE TITLE
Evaluating diagrams using tensor networks

### ISSUE THREAD

**Issue by y-richie-y** [Quantomatic/zxlive#8]
We want the ability to evaluate diagrams using a tensor network library. This can allow us to directly check the semantic equality of 2 ZX diagrams.

**Comment by jvdwetering** [comment]
We discussed a couple of ways this could work. One slightly hacky but potentially nice way to do it, is to check if the user has latex installed, and then asking it to produce a pdf of the matrix. We then view this pdf of the matrix in a window we open, similarly to how tikzit opens a new window with a pdf preview.
PyZX already has a method to output the latex description of a matrix representing a diagram, which has some smarts to make it look nice.

**Comment by RazinShaikh** [comment]
How about using this?
https://gist.github.com/gmarull/dcc8218385014559c1ca46047457c364

**Comment by jvdwetering** [comment]
We can use that, but matplotlib uses a user-installed copy of latex to render it, so this doesn't remove the need to install latex.

**Comment by RazinShaikh** [comment]
The link below says that matplotlib comes with TeX.
https://matplotlib.org/stable/tutorials/text/mathtext.html
> Note that you do not need to have TeX installed, since Matplotlib ships its own TeX expression parser, layout engine, and fonts. The layout engine is a fairly direct adaptation of the layout algorithms in Donald Knuth's TeX, so the quality is quite good (Matplotlib also provides a usetex option for those who do want to call out to TeX to generate their text; see [Text rendering with LaTeX](https://matplotlib.org/stable/tutorials/text/usetex.html)).

**Comment by jvdwetering** [comment]
Oh interesting, although that doesn't mention being able to do matrices. So then we would have to layout the elements ourselves into the matrix if that doesn't work.

**Comment by RazinShaikh** [comment]
Yeah, let's do the minimal amount necessary to display the matrices. If this doesn't work with matrices, then the other simple (but maybe not so pretty as latex) option would be to use `QTableWidget` from QT.
