### ISSUE TITLE
Memory leak and performance issues with sparkles of Magic Wand

### ISSUE THREAD

**Issue by jvdwetering** [Quantomatic/zxlive#80]
If you enable sparkles of the magic wand (with Ctrl+Alt+Shift+S), and you do it for a long time and release you will see that the memory usage of ZXLive is now a couple MB more. In my experiments when I did this three times in a row, the program would just crash without an exception.

When dragging for a long time, the framerate also goes way down, probably because the sparkle objects are not getting destroyed or cleaned up properly.

**Comment by dlyongemallo** [comment]
What are you using to profile the memory usage? I can see in PyCharm's profiler that the sparkles are taking over the CPU if you hold the mouse button down and keep moving the mouse.

Here's what seems to be happening:

- in the `mouseMoveEvent` of `graphview.py`, a call is made to `_emit_sparkles` (if the mode is on)
- the function randomises an angle and speed and creates a `Sparkle`
- a `Sparkle` sets a timer using `QTimeLine` to gradually fade away after 1 second

There's no limit to how frequently or how many times the `mouseMoveEvent` is triggered. The default interval on the timer is [40 ms](https://doc.qt.io/qt-6/qtimeline.html#updateInterval-prop), namely 25 updates a second. This means that if you keep holding down the mouse button and moving the mouse, you're creating possibly thousands of timer steps, each of which does a bit of computation and animation. 

There are a couple of options to deal with this:

- limit the number of total sparkles by removing existing sparkles when new ones are added
- rate-limit sparkle creation (so it doesn't happen on every `mouseMoveEvent`, but only after 100 ms have passed or something like that, or even have an increasing delay between each additional sparkle so you get a lot at the beginning but "run out" of them if you keep holding the mouse)
- hard code the "random" effect with pre-randomised values
- change the interval on the fade timer

Each of these solutions changes the way the sparkles look in a different way, so it's really a matter of preference in terms of what kind of effect you're going for.

**Comment by jvdwetering** [comment]
I would guess limiting the total number of sparkles would be the way to go. It's a silly effect anyway, so it doesn't matter if it is not perfect :)

**Comment by dlyongemallo** [comment]
Hi, @tuomas56,

Would it be okay with you if this issue was assigned to me? I have a fairly good idea of how to fix it.

Thanks.

**Comment by tuomas56** [comment]
Hey @dlyongemallo, sure! I had thought the original version of the code handled this issue by calling `self.scene().removeItem(self)` in the `_timer_step` method of `Sparkle` but evidently this is not the case...
