### ISSUE TITLE
UI for creating custom rewrites

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#83]
ZXLive supports adding custom rewrites. To do so, we can choose a graph file for the left and the right-hand side of the equality. It would be a better experience to have a window for creating custom rewrites. This window should be split vertically, where the user can draw the left and the right-hand side of the rewrite.

**Comment by jvdwetering** [comment]
Agreed, but also I think it would be nice to have the option to save a derivation as a 'lemma'. So you do a bunch in rewrites in Proof mode, and then you can say, okay this set of rewrites that led to the final graph is now a new lemma.

**Comment by RazinShaikh** [comment]
That is a great idea👍
In terms of implementation, the ZXLive proof file has enough information (i.e. first and last graphs) to create a rewrite. If we first figure out how the rewrites are stored and retrieved (ref. #84 ), adding this functionality in the UI should be relatively easy.
