### ISSUE TITLE
Bialgebra animation skips animating the initial vertex movement

### ISSUE THREAD

**Issue by RazinShaikh** [Quantomatic/zxlive#86]
https://github.com/Quantomatic/zxlive/assets/28257517/bdd4abf6-c173-4f31-8358-9aab400c9dee

**Comment by dlyongemallo** [comment]
What's the desired output here? That the two vertices first fuse in the middle and then the four new vertices move out from there, or each of the original two vertices first turn into two overlapping vertices of the other colour?

**Comment by RazinShaikh** [comment]
I would say "That the two vertices first fuse in the middle and then the four new vertices move out from there" is probably the desired output

**Comment by dlyongemallo** [comment]
Output of PR #124:
[Screencast from 2023-09-29 08:15:57 PM.webm](https://github.com/Quantomatic/zxlive/assets/9248532/692f1da2-f25f-449a-b7d0-b3f6c0126b59)
