### ISSUE TITLE
Weird naming of Graphs

### ISSUE THREAD

**Issue by boldar99** [Quantomatic/zxlive#90]
Why do we do this with the naming of the Graphs, @jvdwetering? 

![image](https://github.com/Quantomatic/zxlive/assets/49209650/16d23493-9bc5-4a35-89f1-010f531eed8f)

**Comment by jvdwetering** [comment]
This is so that if we want to change the graph backend from pyzx in ZXLive, we can just change it in a single line here, instead of doing it in every single file that talks about graphs.

**Comment by RazinShaikh** [comment]
In that case, we need to fix all other places in the code that directly imports GraphS from pyzx

**Comment by jvdwetering** [comment]
Yes, we should :)

**Comment by wlcsm** [comment]
I think this was resolved in https://github.com/Quantomatic/zxlive/commit/847d14cd24d37d5f51969ef10dce0b90de128f38

I can't find any other instances of GraphS other than in the type alias

```
$ grep 'GraphS\>' -R zxlive
zxlive/common.py:GraphT: TypeAlias = pyzx.graph.graph_s.GraphS
```
